version: '3'

services:
  api:
    image: aluraflix-api:latest
    container_name: api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${DB_URI}
      - SECRET_KEY=${JWT_KEY}
    links:
      - database

  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"

  mongo-express:
    container_name: express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_URL: ${DB_URI}